.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.TH camview 1 
.SH NAME
camview \- Image stream viewer
.SH SYNOPSIS
.TP 5
\fBcamview \fI[options]\fR

.SH DESCRIPTION
.PP
\fBcamview\fR is a graphical tool for viewing and testing image processing
chains.  It uses GTK+ 2.0, OpenGL, and libcamunits.

.SH OPTIONS
The following options are provided by \fBcamview\fR using the standard GNU
command line syntax:
.TP
.B \-c, \-\-chain=\fINAME\fB
Load chain from file NAME
.TP
.B \-\-no\-gui
Run without a GUI.  If --no-gui is specified, -c is required.
.TP
.B \-\-plugin\-path=\fIPATH\fB
Add the directories in PATH to the plugin search path.  PATH should be a
colon-delimited list.
.TP
.B \-h, \-\-help
Print this help and exit.

.SH AUTHORS

 Albert Huang <\fIashuang@alum.mit.edu\fR>
.br
 David Moore <\fIdcm@acm.org\fR>
