######################################################################
# Automatically generated by qmake (2.01a) Wed May 14 17:03:43 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CamUnitChainQtAdapter.hpp 
SOURCES += CamUnitChainQtAdapter.cpp snapshot.cpp

CONFIG += link_pkgconfig
PKGCONFIG += camunits glib-2.0 gobject-2.0 gmodule-2.0
